version: '3'

services:

  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    networks:
      - timecard
    environment:
      - PROD_HOST_IP=$PROD_HOST_IP
      - ENV=$ENV
    container_name: my-client-container

  api:
    build:
      context: ./backend
    ports: 
      - '5000:5000'
    networks:
      - timecard
    environment:
      - SESSION_SECRET_KEY=$SESSION_SECRET_KEY
      - ELASTIC_EMAIL_API_KEY=$ELASTIC_EMAIL_API_KEY
      - MONGODB_CONNECTION_URL=$MONGODB_CONNECTION_URL
      - PROD_HOST_IP=$PROD_HOST_IP
      - ENV=$ENV
    container_name: my-api-container

  nginx:
    image: nginx
    build: ./nginx
    ports:
      - 80:3050
    depends_on:
      - api
      - client
    networks:
      - timecard
    container_name: my-nginx-container

networks:
  timecard:
    driver: bridge


    