version: '3'

services:
  client:
    build:
      context: ./client
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - api

  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3050:3050"
    networks:
      - app-network
    depends_on:
      - client

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_CONNECTION_URL=$MONGODB_CONNECTION_URL
    volumes:
      - ./data:/data/db

  api:
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
      - ./logs:/logs
    environment:
      - SESSION_SECRET_KEY=$SESSION_SECRET_KEY
      - ELASTIC_EMAIL_API_KEY=$ELASTIC_EMAIL_API_KEY
    networks:
      - app-network

networks:
  app-network:
    driver: bridge      