

GET http://localhost:5000/posts/ HTTP/1.1
Content-Type: application/json

{

}
###
POST http://localhost:5000/posts/ HTTP/1.1
Content-Type: application/json

{
    "title":"title1",
    "text":"here is sopme text for the main body of the post",
    "image":"https://en.wikipedia.org/static/images/icons/wikipedia.png"
}

